### ISSUE TITLE
BUG: UI-TESTING (Themes)

### ISSUE THREAD

**Issue by steffenkux** [dm3-org/dm3#773]
### TESTED VERSION: NPM-Package @dm3-org/dm3-messenger-widget V.1.0.13

> **PRIO1** ... critical bug, blocks usage
> **PRIO2** ... bug, but doesn't block usage
> **PRIO3** ... not nice, not critical for release

Integration:
New REACT app, added package, added .env, added component in App.ts.
```JavaScript
<div className="dm3-container">
   <DM3 {...props} />
</div>
```
with CSS
```CSS
.dm3-container {
  width: 100%; /*  mandatory property  */
  height: 100%; /*  mandatory property  */
  border-radius: 5px; /*  optional property  */
  overflow: hidden; /*  needed only when border-radius property is set */
}
```
## AIM OF THE TEST

customizing the component to the user's L&F

## BUGS:

- [x] **(PRIO3)** Misspelling: chatBakgroundColor
- [x] **(PRIO2)** NOT working: receivedMessageTextColor, sentMessageTextColor (see picture (01) -  both colors are set to "red" (used color is primaryTextColor)
- [x] **(PRIO3)** Line doesn't go to the bottom (see picture 02) --> REQ: line goes completely to the bottom
- [x] **(PRIO2)** The background color for reactions is wrong (must be the same as the message bubble). Both:  for ended and received messages (see picture (03)) 
- [x] **(PRIO2)** I can remove a reaction from the other user by clicking on it --> REQ: remove reaction is onöy possible for my own reactions

## IMAGES

(01) 
![image](https://github.com/dm3-org/dm3/assets/26625404/ade6aa80-a168-4ed3-8790-b8c7f9841eb3)

(02)
![image](https://github.com/dm3-org/dm3/assets/26625404/0bfd9933-db2b-4fc3-bc9f-a2ed21dd028a)

(03)
![image](https://github.com/dm3-org/dm3/assets/26625404/15fa366a-875f-49f8-82a4-dabbf596717f)
